/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactFormSubmission {
  'name' : string,
  'email' : string,
  'company' : [] | [string],
  'message' : string,
}
export interface JobApplication {
  'name' : string,
  'jobId' : string,
  'email' : string,
  'resumeLink' : string,
  'message' : [] | [string],
  'phone' : string,
}
export interface JobPosting {
  'title' : string,
  'salary' : string,
  'responsibilities' : string,
  'jobId' : string,
  'description' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'company' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addJobApplication' : ActorMethod<[JobApplication], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllApplications' : ActorMethod<
    [],
    Array<[string, Array<JobApplication>]>
  >,
  'getAllContactFormSubmissions' : ActorMethod<
    [],
    Array<ContactFormSubmission>
  >,
  'getAllJobs' : ActorMethod<[], Array<JobPosting>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompanyContacts' : ActorMethod<
    [],
    { 'email' : string, 'address' : string, 'phone' : string }
  >,
  'getJobById' : ActorMethod<[string], [] | [JobPosting]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<[ContactFormSubmission], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];