/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const JobApplication = IDL.Record({
  'name' : IDL.Text,
  'jobId' : IDL.Text,
  'email' : IDL.Text,
  'resumeLink' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactFormSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
});
export const JobPosting = IDL.Record({
  'title' : IDL.Text,
  'salary' : IDL.Text,
  'responsibilities' : IDL.Text,
  'jobId' : IDL.Text,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'company' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addJobApplication' : IDL.Func([JobApplication], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllApplications' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(JobApplication)))],
      ['query'],
    ),
  'getAllContactFormSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getAllJobs' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompanyContacts' : IDL.Func(
      [],
      [
        IDL.Record({
          'email' : IDL.Text,
          'address' : IDL.Text,
          'phone' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getJobById' : IDL.Func([IDL.Text], [IDL.Opt(JobPosting)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactForm' : IDL.Func([ContactFormSubmission], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const JobApplication = IDL.Record({
    'name' : IDL.Text,
    'jobId' : IDL.Text,
    'email' : IDL.Text,
    'resumeLink' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactFormSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
  });
  const JobPosting = IDL.Record({
    'title' : IDL.Text,
    'salary' : IDL.Text,
    'responsibilities' : IDL.Text,
    'jobId' : IDL.Text,
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'company' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addJobApplication' : IDL.Func([JobApplication], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllApplications' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(JobApplication)))],
        ['query'],
      ),
    'getAllContactFormSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getAllJobs' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompanyContacts' : IDL.Func(
        [],
        [
          IDL.Record({
            'email' : IDL.Text,
            'address' : IDL.Text,
            'phone' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getJobById' : IDL.Func([IDL.Text], [IDL.Opt(JobPosting)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactForm' : IDL.Func([ContactFormSubmission], [], []),
  });
};

export const init = ({ IDL }) => { return []; };