/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const EducationEntry = IDL.Record({
  'startYear' : IDL.Nat,
  'endYear' : IDL.Opt(IDL.Nat),
  'institution' : IDL.Text,
  'degree' : IDL.Text,
  'fieldOfStudy' : IDL.Text,
});
export const WorkExperience = IDL.Record({
  'startYear' : IDL.Nat,
  'endYear' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'companyName' : IDL.Text,
  'position' : IDL.Text,
});
export const JobApplication = IDL.Record({
  'resume' : IDL.Opt(ExternalBlob),
  'country' : IDL.Text,
  'termsAccepted' : IDL.Bool,
  'education' : IDL.Vec(EducationEntry),
  'jobId' : IDL.Text,
  'email' : IDL.Text,
  'passoutYear' : IDL.Nat,
  'previousWorkplaces' : IDL.Vec(WorkExperience),
  'message' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'expectedPay' : IDL.Text,
  'currentLocation' : IDL.Text,
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'collegeUniversityName' : IDL.Text,
  'totalWorkExperience' : IDL.Text,
  'firstName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactFormSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
});
export const ExperienceRange = IDL.Record({
  'maxYears' : IDL.Nat,
  'minYears' : IDL.Nat,
});
export const JobPosting = IDL.Record({
  'title' : IDL.Text,
  'responsibilities' : IDL.Text,
  'jobId' : IDL.Text,
  'description' : IDL.Text,
  'experienceRange' : ExperienceRange,
  'salaryRange' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'company' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addJobApplication' : IDL.Func([JobApplication], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllApplications' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(JobApplication)))],
      ['query'],
    ),
  'getAllContactFormSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getAllJobs' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompanyContacts' : IDL.Func(
      [],
      [
        IDL.Record({
          'email' : IDL.Text,
          'address' : IDL.Text,
          'phone' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getJobById' : IDL.Func([IDL.Text], [IDL.Opt(JobPosting)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactForm' : IDL.Func([ContactFormSubmission], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const EducationEntry = IDL.Record({
    'startYear' : IDL.Nat,
    'endYear' : IDL.Opt(IDL.Nat),
    'institution' : IDL.Text,
    'degree' : IDL.Text,
    'fieldOfStudy' : IDL.Text,
  });
  const WorkExperience = IDL.Record({
    'startYear' : IDL.Nat,
    'endYear' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'companyName' : IDL.Text,
    'position' : IDL.Text,
  });
  const JobApplication = IDL.Record({
    'resume' : IDL.Opt(ExternalBlob),
    'country' : IDL.Text,
    'termsAccepted' : IDL.Bool,
    'education' : IDL.Vec(EducationEntry),
    'jobId' : IDL.Text,
    'email' : IDL.Text,
    'passoutYear' : IDL.Nat,
    'previousWorkplaces' : IDL.Vec(WorkExperience),
    'message' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'expectedPay' : IDL.Text,
    'currentLocation' : IDL.Text,
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'collegeUniversityName' : IDL.Text,
    'totalWorkExperience' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactFormSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
  });
  const ExperienceRange = IDL.Record({
    'maxYears' : IDL.Nat,
    'minYears' : IDL.Nat,
  });
  const JobPosting = IDL.Record({
    'title' : IDL.Text,
    'responsibilities' : IDL.Text,
    'jobId' : IDL.Text,
    'description' : IDL.Text,
    'experienceRange' : ExperienceRange,
    'salaryRange' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'company' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addJobApplication' : IDL.Func([JobApplication], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllApplications' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(JobApplication)))],
        ['query'],
      ),
    'getAllContactFormSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getAllJobs' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompanyContacts' : IDL.Func(
        [],
        [
          IDL.Record({
            'email' : IDL.Text,
            'address' : IDL.Text,
            'phone' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getJobById' : IDL.Func([IDL.Text], [IDL.Opt(JobPosting)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactForm' : IDL.Func([ContactFormSubmission], [], []),
  });
};

export const init = ({ IDL }) => { return []; };